### ISSUE TITLE
Add generics to go 1.18 container

### ISSUE THREAD

**Issue by grisu48** [SUSE/BCI-tests#118]
Since generics are introduced in go 1.18 we should add a simple test run to test generics there (and there only).

**Comment by dcermak** [comment]
I would suggest to find a project that uses them and build it in the go test suite, similarly to how we build `kured`.

**Comment by grisu48** [comment]
Will work on this now.

**Comment by dcermak** [comment]
Do you want to close this now that #133 is merged?

**Comment by grisu48** [comment]
Yep, I think this issue has been resolved. Thanks Dan!
