### ISSUE TITLE
Run CI pipelines only for affected changes

### ISSUE THREAD

**Issue by jlausuch** [SUSE/BCI-tests#164]
We are running the full pipeline list of tests for each new commit/PR. Sometimes, the changes are done in specific test environment and we could limit those runs to only run that environment. This way, we could save time and unnecessary resources, and specially ci failures that have nothing to do with the change under review.

**Comment by dcermak** [comment]
Jose Lausuch ***@***.***> writes:

> We are running the full pipeline list of tests for each new commit/PR. Sometimes, the changes are done in specific test environment and we could limit those runs to only run that environment. This way, we could save time and unnecessary resources, and specially ci failures that have nothing to do with the change under review.

This is theoretically possible by triggering jobs on a file/folder change:
https://www.techielass.com/trigger-a-github-action-workflow-when-a-folder-changes/
But I don't really know how to do this stuff dynamically, as we generate
the jobs on the fly.

Also, this will most certainly mess with tests being required to pass
for a PR to be accepted.

**Comment by dcermak** [comment]
Unfortunately this is currently not possible in github actions, as we generate the jobs dynamically but one can only filter workflows whole workflows via paths.
