### ISSUE TITLE
Write test for distribution-image

### ISSUE THREAD

**Issue by grisu48** [SUSE/BCI-tests#185]
We need a new test run for our `distribution-image` (See [distribution](https://github.com/distribution/distribution) - it's basically a container registry).

I'm thinking of a simple push and pull test run, so we would need to create a container, and in one test function push a container to the registry, which is pulled in another test run. Or we do this in one function.

Related ticket: https://progress.opensuse.org/issues/120810

**Comment by dcermak** [comment]
I would strongly suggest to perform these actions in one function. When you use pytest with xdist, then it is more or less impossible to schedule test functions. Then all you have to do is to create the distribution container via the `*container_per_test` fixture and push & pull to it (which I guess happens via http?)

**Comment by grisu48** [comment]
Makes sense. I think the most difficult part here will be to have a test run that runs outside the container. We want to basically spin up the container and then run `[podman|docker] [pull|push]` **against** the container not **in** the container.

Do we already have a test run that does something similar that could be used as example?

**Comment by dcermak** [comment]
Anything using the `host` fixture runs on the host system and not inside a container, e.g.: https://github.com/SUSE/BCI-tests/blob/e8ebd886c02a9466292631c0c316454c95b35817/tests/test_go.py#L156

**Comment by grisu48** [comment]
> Anything using the `host` fixture runs on the host system and not inside a container, e.g.:
> 
> https://github.com/SUSE/BCI-tests/blob/e8ebd886c02a9466292631c0c316454c95b35817/tests/test_go.py#L156

@mloviska this might come in useful when writing the test!

**Comment by dcermak** [comment]
Test for the distribution image have been added via #198. Is there anything else left to test @grisu48 @mloviska @jlausuch?

**Comment by mloviska** [comment]
> Test for the distribution image have been added via #198. Is there anything else left to test @grisu48 @mloviska @jlausuch?

Good question, as of now, we do not add any certificates, the registry is insecure. Other than that, I think we are fine.

**Comment by dcermak** [comment]
@dirkmueller What do you think, do we need additional tests?

**Comment by dirkmueller** [comment]
I think there's never enough tests, but there are some, so let's close it
