### ISSUE TITLE
Add performance testing

### ISSUE THREAD

**Issue by dcermak** [SUSE/BCI-tests#41]
@dirkmueller anything in particular that you'd like to check?

**Comment by evrardjp** [comment]
I have started a PR with that, for which we have a new tox unit (therefore we have a single isolated test). That tox unit will not fetch the containers in advance, and should build everything in one place. The test timings from pytest (through junit output) is a good start, but if we need more details, we should maybe add a pytest plugin.

**Comment by grisu48** [comment]
Performance tests on openQA are almost impossible to do, because we are always using shared workers with no guarantees at all.

**Comment by dcermak** [comment]
This issue is so old, if it were a kid, it would be in kindergarten right now. I think the scope of this project changed sufficiently to consider it no longer relevant
