### ISSUE TITLE
Slow CI

### ISSUE THREAD

**Issue by alexandrevicenzi** [SUSE/BCI-tests#447]
The CI has become slow, but it is weird, the same test runs for 10 min one day and 1 hour the other day.  We might be hitting a rate limit or similar.

We need to identify what causes our CI to be slow sometimes and if possible find a solution.

**Comment by dirkmueller** [comment]
@alexandrevicenzi I think the situation improved. agree to close? or do we want to land the pytest print-slowest-run patch? I'd be in favor of that.

**Comment by alexandrevicenzi** [comment]
@dirkmueller I believe we can close this, but I think we should merge #446.
