### ISSUE TITLE
Need to ensure size of containers to match embedded use cases

### ISSUE THREAD

**Issue by evrardjp** [SUSE/BCI-tests#68]
There are ISVs which are looking for runtime containers which size don't go above 50MB (without software). We should ensure that runtime containers never exceed that size.

**Comment by evrardjp** [comment]
I think we can argue on the value of 50MB as "base image without software" doesn't mean much. e.g. for go, one can have the runtime image as "scratch" and therefore it will always be 0 MB. We need to justify other runtimes, and explain how small they are.

**Comment by dirkmueller** [comment]
we gave sizing tests for the base containers (https://github.com/SUSE/BCI-tests/blob/ea5dec3dddb95f47cab9a8dda2d752621a955ff2/tests/test_base.py#L19-L25 )
