### ISSUE TITLE
run tests on SLE Base Container (using SLE BCI repository)

### ISSUE THREAD

**Issue by fcrozat** [SUSE/BCI-tests#89]
In addition to openSUSE BCI image, the testsuite should also be running on SLE Base Image, which is now setup with SLE_BCI repository. No SCC enablement is needed.

**Comment by dcermak** [comment]
Frederic Crozat ***@***.***> writes:

> In addition to openSUSE BCI image, the testsuite should also be running on SLE Base Image, which is now setup with SLE_BCI repository. No SCC enablement is needed.

What do you want tested in these images? Which requirements should they
fulfill?

**Comment by dirkmueller** [comment]
I think that's a great question, my suggestion is to test the zypper install lines from the `github.com/rancher/rancher/package/Dockerfile*` and `Dockerfile.dapper`  for now, to ensure that we don't break that?

**Comment by dirkmueller** [comment]
we could also test that without registration and with registration we get the same base result, and maybe also that we get the "extra" with registration.

**Comment by mvarlese** [comment]
As a last comer to the party I agree with @dirkmueller 
I'd like to see rancher/rancher being one of the platforms used to validate our SLE BCI images. Similarly to what we previously did with rancher/fleet.
